# Generated by Django 5.2.17 on 2026-10-05 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(max_length=40, verbose_name="teléfono")),
                (
                    "direccion",
                    models.CharField(
                        max_length=200, verbose_name="dirección de entrega"
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("compra_individual", "Compra individual"),
                            ("sostenedor", "Sostenedor"),
                            ("regenerador", "Regenerador"),
                            ("guardian", "Guardián"),
                        ],
                        default="compra_individual",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
