# Generated by Django 5.2.17 on 2026-10-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0002_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="nivel",
        ),
    ]
