# Generated by Django 5.2.17 on 2026-10-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0003_cliente_nivel_calculado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administración"),
                    ("chofer", "Chofer (solo carga retiros)"),
                    ("planta", "Planta (clasifica retiros y lleva los lotes)"),
                    ("granja", "Granja (registro diario)"),
                    ("operador", "Operador de campo (todas las tareas de campo)"),
                    ("restaurante", "Restaurante"),
                    ("cliente", "Cliente"),
                    ("carbosur", "CarboSur (solo lectura)"),
                ],
                default="cliente",
                max_length=20,
            ),
        ),
    ]
