# Generated by Django 5.2.17 on 2026-10-05 16:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cuentas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "fecha_inicio",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="fecha de inicio",
                    ),
                ),
                (
                    "bandejas",
                    models.PositiveIntegerField(verbose_name="bandejas generadas"),
                ),
                (
                    "g_neonatos",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="neonatos utilizados (g)",
                    ),
                ),
                (
                    "fecha_cosecha",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de cosecha"
                    ),
                ),
                (
                    "kg_larvas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="larvas (kg)",
                    ),
                ),
                (
                    "kg_frass",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="frass (kg)",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_inicio", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RegistroGranja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate, unique=True
                    ),
                ),
                (
                    "huevos",
                    models.PositiveIntegerField(verbose_name="huevos producidos"),
                ),
                (
                    "kg_larvas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="larvas para las gallinas (kg)",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional: de qué lote salieron las larvas.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_granja",
                        to="captura.lote",
                        verbose_name="lote de las larvas",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de granja",
                "verbose_name_plural": "registros de granja",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Retiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "kg_levantados",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="levantado (kg)",
                    ),
                ),
                (
                    "kg_impropios",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="impropios (kg)",
                    ),
                ),
                (
                    "kg_restos_vegetales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="restos vegetales (kg)",
                    ),
                ),
                (
                    "kg_residuos_plato",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="residuos de plato (kg)",
                    ),
                ),
                (
                    "kg_no_ingresa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="no entra a Eggologic (kg)",
                    ),
                ),
                (
                    "no_ingresa_estimado",
                    models.BooleanField(
                        default=False, verbose_name="ese dato es una estimación"
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retiros",
                        to="captura.lote",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retiros",
                        to="cuentas.restaurante",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
