# Generated by Django 5.2.17 on 2026-10-05 17:15

import captura.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captura", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="retiro",
            name="foto",
            field=models.FileField(
                blank=True,
                upload_to="retiros/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "heic", "heif"]
                    ),
                    captura.models.validar_tamano_foto,
                ],
            ),
        ),
        migrations.AddField(
            model_name="retiro",
            name="latitud",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="retiro",
            name="longitud",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="retiro",
            name="precision_m",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="precisión de la ubicación (m)"
            ),
        ),
    ]
