# Generated by Django 5.2.17 on 2026-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captura", "0002_retiro_foto_y_ubicacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("contenido", models.BinaryField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
