# Generated by Django 5.2.17 on 2026-10-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captura", "0003_archivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrogranja",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                help_text="Opcional: de qué lote salieron las larvas.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros_granja",
                to="captura.lote",
                verbose_name="lote de las larvas",
            ),
        ),
        migrations.AlterField(
            model_name="retiro",
            name="lote",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="retiros",
                to="captura.lote",
            ),
        ),
    ]
