# Generated by Django 5.2.17 on 2026-10-06 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cuentas", "0003_cliente_nivel_calculado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.DateField(help_text="Primer día del mes.")),
                ("retiros", models.PositiveIntegerField()),
                (
                    "kg_organicos",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="kg orgánicos"
                    ),
                ),
                (
                    "tco2e_linea_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="tCO2e línea de base",
                    ),
                ),
                (
                    "tco2e_proyecto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="tCO2e del proyecto",
                    ),
                ),
                (
                    "tco2e_fugas",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="tCO2e de fugas"
                    ),
                ),
                (
                    "tco2e_neto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="tCO2e evitadas (neto)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_cola", "Verificado, por enviar"),
                            ("enviado", "Enviado, falta la aprobación"),
                            ("registrado", "Registrado"),
                        ],
                        default="en_cola",
                        max_length=20,
                    ),
                ),
                ("verificado_en", models.DateTimeField(auto_now_add=True)),
                ("registrado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "intentos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="intentos fallidos"
                    ),
                ),
                (
                    "ultimo_error",
                    models.TextField(blank=True, verbose_name="último error"),
                ),
                (
                    "restaurante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reportes",
                        to="cuentas.restaurante",
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte mensual",
                "verbose_name_plural": "reportes mensuales",
                "ordering": ["-mes", "restaurante__codigo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("restaurante", "mes"),
                        name="un_reporte_por_restaurante_y_mes",
                    )
                ],
            },
        ),
    ]
