# Generated by Django 5.2.17 on 2026-10-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guardian", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportemensual",
            name="mensaje_hcs",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="mensaje en HCS"
            ),
        ),
        migrations.AddField(
            model_name="reportemensual",
            name="topic_hcs",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="topic de HCS"
            ),
        ),
    ]
